### PR TITLE
Update "ember-cli-babel" to v6.9.0

### PR DESCRIPTION
**Pull request by Turbo87**
/cc @workmanw @rwjblue

### CODE REVIEW

**Comment by cibernox** [comment]
I was about to make the exact same PR 👍

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
Note that this is not a breaking change at all (our `engines` in `package.json` already stated `>= 4`). 

I can merge but not release to NPM...  

@workmanw - Can you do the honors?

**Comment by workmanw** [comment]
@rwjblue I'm on it. I'm also going to give you NPM access.

**Comment by workmanw** [comment]
Published v0.2.1 .

**Comment by rwjblue** [comment]
Thank you!

**Pull request merged**
