### PR TITLE
prevent caught assertions from being logged

### PR DESCRIPTION
**Pull request by kturney**
on top of https://github.com/workmanw/ember-qunit-assert-helpers/pull/15

### CODE REVIEW

**Comment by rwjblue** [comment]
Mind rebasing?

**Review by rwjblue — COMMENTED** [review]
LGTM, once rebased

**Review by workmanw — APPROVED** [review]
Thanks!!!

**Comment by kturney** [comment]
Hi gents.

Any thoughts on merging and publishing this?

**Comment by rwjblue** [comment]
I don't know that I can publish (haven't really ever tried).  

@workmanw - You happen to have time to do it?

**Comment by workmanw** [comment]
I definitely do. I'll do this today. I have another addon to catch up on maintenance wise.

**Comment by workmanw** [comment]
Sorry, I didn't catch this the first time, but the addition of using `Testem.handleConsoleMessage` seems to break the tests when I run it locally using `ember serve`. I'm wondering if instead of stubbing out `Testem.handleConsoleMessage`, we should instead just stub out `Ember.Logger.error`. 

Do you guys think that is sufficient to test this? Or I could check if `Testem` is defined and act accordingly.

**Comment by rwjblue** [comment]
I think stubbing Ember.Logger.error is fine, but we have to make sure to capture it early enough (since we now replace it in normal non-test code too).

**Comment by kturney** [comment]
Ah. Interesting. I forgot about running tests from `ember serve` /tests.

**Comment by kturney** [comment]
I've submitted https://github.com/workmanw/ember-qunit-assert-helpers/pull/17 to fix this

**Comment by workmanw** [comment]
@kturney Published as `0.2.0`. Thanks again.

**Pull request merged**
